/**
 * veed/subtitles source-language codes (BCP-47). Matches the `language`
 * input on the model — improving transcription accuracy when it matches the
 * audio. Source of truth: https://fal.ai/models/veed/subtitles
 *
 * Two exports:
 *   - `SUBTITLE_LANGUAGE_VALUES` — the literal union used for zod validation
 *     and runtime narrowing. Keep in sync with `SUBTITLE_LANGUAGES` below.
 *   - `SUBTITLE_LANGUAGES` — UI list of `{ value, label }` (uniform shape so
 *     the combobox generic infers a single item type).
 */

export const SUBTITLE_LANGUAGE_VALUES = [
  // English variants
  "en-US",
  "en-GB",
  "en-AU",
  "en-IN",
  "en-NZ",
  // Other major languages
  "es-ES",
  "es-MX",
  "es-AR",
  "fr-FR",
  "fr-CA",
  "de-DE",
  "it-IT",
  "pt-BR",
  "pt-PT",
  "nl-NL",
  "pl-PL",
  "ru-RU",
  "uk-UA",
  "tr-TR",
  "sv-SE",
  "da-DK",
  "nb-NO",
  "fi-FI",
  "cs-CZ",
  "sk-SK",
  "hu-HU",
  "ro-RO",
  "el-GR",
  "bg-BG",
  "hr-HR",
  "sr-RS",
  "sl-SI",
  "is-IS",
  "et-EE",
  "lv-LV",
  "lt-LT",
  "ca-ES",
  "gl-ES",
  "eu-ES",
  "mt-MT",
  "ga",
  "cy-GB",
  "gd",
  "he-IL",
  "ar-SA",
  "ar-AE",
  "ar-EG",
  "fa-IR",
  "ur-IN",
  "ur-PK",
  "hi",
  "bn",
  "pa",
  "gu",
  "ta",
  "te",
  "kn",
  "ml",
  "mr",
  "si",
  "th-TH",
  "lo-LA",
  "km",
  "my",
  "vi-VN",
  "id-ID",
  "ms-MY",
  "jv-ID",
  "su-ID",
  "fil-PH",
  "ceb-PH",
  "mi-NZ",
  "haw",
  "ja-JP",
  "ko-KR",
  "zh",
  "zh-HK",
  "zh-TW",
  "yue-Hant-HK",
  "mn-MN",
  "kk-KZ",
  "ky-KG",
  "uz-UZ",
  "tg-TJ",
  "tk",
  "az-AZ",
  "hy-AM",
  "ka-GE",
  "am-ET",
  "ti",
  "sw-KE",
  "sw-TZ",
  "zu-ZA",
  "xh-ZA",
  "af-ZA",
  "yo-NG",
  "ig",
  "ha-NG",
  "so-SO",
  "mg",
  "sm",
  "to",
  "fj",
  "ht",
] as const;

export type SubtitleLanguage = (typeof SUBTITLE_LANGUAGE_VALUES)[number];
export const DEFAULT_SUBTITLE_LANGUAGE: SubtitleLanguage = "en-GB";

export function isSubtitleLanguage(value: string): value is SubtitleLanguage {
  return (SUBTITLE_LANGUAGE_VALUES as readonly string[]).includes(value);
}

export type SubtitleLanguageEntry = {
  value: SubtitleLanguage;
  label: string;
};

/**
 * UI list (code → human label). Uniform shape so `<Combobox items={...}>`
 * infers a single item type. Keep the codes in sync with
 * `SUBTITLE_LANGUAGE_VALUES` above.
 */
export const SUBTITLE_LANGUAGES: readonly SubtitleLanguageEntry[] = [
  { value: "en-US", label: "English (US)" },
  { value: "en-GB", label: "English (UK)" },
  { value: "en-AU", label: "English (Australia)" },
  { value: "en-IN", label: "English (India)" },
  { value: "en-NZ", label: "English (New Zealand)" },
  { value: "es-ES", label: "Spanish (Spain)" },
  { value: "es-MX", label: "Spanish (Mexico)" },
  { value: "es-AR", label: "Spanish (Argentina)" },
  { value: "fr-FR", label: "French (France)" },
  { value: "fr-CA", label: "French (Canada)" },
  { value: "de-DE", label: "German" },
  { value: "it-IT", label: "Italian" },
  { value: "pt-BR", label: "Portuguese (Brazil)" },
  { value: "pt-PT", label: "Portuguese (Portugal)" },
  { value: "nl-NL", label: "Dutch" },
  { value: "pl-PL", label: "Polish" },
  { value: "ru-RU", label: "Russian" },
  { value: "uk-UA", label: "Ukrainian" },
  { value: "tr-TR", label: "Turkish" },
  { value: "sv-SE", label: "Swedish" },
  { value: "da-DK", label: "Danish" },
  { value: "nb-NO", label: "Norwegian (Bokmål)" },
  { value: "fi-FI", label: "Finnish" },
  { value: "cs-CZ", label: "Czech" },
  { value: "sk-SK", label: "Slovak" },
  { value: "hu-HU", label: "Hungarian" },
  { value: "ro-RO", label: "Romanian" },
  { value: "el-GR", label: "Greek" },
  { value: "bg-BG", label: "Bulgarian" },
  { value: "hr-HR", label: "Croatian" },
  { value: "sr-RS", label: "Serbian" },
  { value: "sl-SI", label: "Slovenian" },
  { value: "is-IS", label: "Icelandic" },
  { value: "et-EE", label: "Estonian" },
  { value: "lv-LV", label: "Latvian" },
  { value: "lt-LT", label: "Lithuanian" },
  { value: "ca-ES", label: "Catalan" },
  { value: "gl-ES", label: "Galician" },
  { value: "eu-ES", label: "Basque" },
  { value: "mt-MT", label: "Maltese" },
  { value: "ga", label: "Irish" },
  { value: "cy-GB", label: "Welsh" },
  { value: "gd", label: "Scottish Gaelic" },
  { value: "he-IL", label: "Hebrew" },
  { value: "ar-SA", label: "Arabic (Saudi Arabia)" },
  { value: "ar-AE", label: "Arabic (UAE)" },
  { value: "ar-EG", label: "Arabic (Egypt)" },
  { value: "fa-IR", label: "Persian" },
  { value: "ur-IN", label: "Urdu (India)" },
  { value: "ur-PK", label: "Urdu (Pakistan)" },
  { value: "hi", label: "Hindi" },
  { value: "bn", label: "Bengali" },
  { value: "pa", label: "Punjabi" },
  { value: "gu", label: "Gujarati" },
  { value: "ta", label: "Tamil" },
  { value: "te", label: "Telugu" },
  { value: "kn", label: "Kannada" },
  { value: "ml", label: "Malayalam" },
  { value: "mr", label: "Marathi" },
  { value: "si", label: "Sinhala" },
  { value: "th-TH", label: "Thai" },
  { value: "lo-LA", label: "Lao" },
  { value: "km", label: "Khmer" },
  { value: "my", label: "Burmese" },
  { value: "vi-VN", label: "Vietnamese" },
  { value: "id-ID", label: "Indonesian" },
  { value: "ms-MY", label: "Malay" },
  { value: "jv-ID", label: "Javanese" },
  { value: "su-ID", label: "Sundanese" },
  { value: "fil-PH", label: "Filipino" },
  { value: "ceb-PH", label: "Cebuano" },
  { value: "mi-NZ", label: "Maori" },
  { value: "haw", label: "Hawaiian" },
  { value: "ja-JP", label: "Japanese" },
  { value: "ko-KR", label: "Korean" },
  { value: "zh", label: "Chinese (Simplified)" },
  { value: "zh-HK", label: "Chinese (Hong Kong)" },
  { value: "zh-TW", label: "Chinese (Traditional)" },
  { value: "yue-Hant-HK", label: "Chinese (Cantonese)" },
  { value: "mn-MN", label: "Mongolian" },
  { value: "kk-KZ", label: "Kazakh" },
  { value: "ky-KG", label: "Kyrgyz" },
  { value: "uz-UZ", label: "Uzbek" },
  { value: "tg-TJ", label: "Tajik" },
  { value: "tk", label: "Turkmen" },
  { value: "az-AZ", label: "Azerbaijani" },
  { value: "hy-AM", label: "Armenian" },
  { value: "ka-GE", label: "Georgian" },
  { value: "am-ET", label: "Amharic" },
  { value: "ti", label: "Tigrinya" },
  { value: "sw-KE", label: "Swahili (Kenya)" },
  { value: "sw-TZ", label: "Swahili (Tanzania)" },
  { value: "zu-ZA", label: "Zulu" },
  { value: "xh-ZA", label: "Xhosa" },
  { value: "af-ZA", label: "Afrikaans" },
  { value: "yo-NG", label: "Yoruba" },
  { value: "ig", label: "Igbo" },
  { value: "ha-NG", label: "Hausa" },
  { value: "so-SO", label: "Somali" },
  { value: "mg", label: "Malagasy" },
  { value: "sm", label: "Samoan" },
  { value: "to", label: "Tongan" },
  { value: "fj", label: "Fijian" },
  { value: "ht", label: "Haitian Creole" },
];